ormi3-final-project-team/nolreo_wassup_BE

- README.md
- 수정파일 .\README.md
- 수정내용 API 명세서 추가
> :memo: Doc: README.md API 명세 추가

- account/managers.py
- account/models.py
- requirements.txt
- 수정 파일
.\account\models.py
- 생성 파일
.\accounts\managers.py
- 수정 사항
사용자와 슈퍼유저가 email을 로그인 수단으로 사용하기 위한 코드 구현
> ✨ Feat: User모델 추가

- traffic/serializers.py
- traffic/tests.py
- traffic/urls.py
- traffic/views.py
✨ Feat: 버스 생성 기능
- 생성 파일
.\traffic\serializers.py
- 수정 파일
.\traffic\serializers.py
.\traffic\urls.py
.\traffic\views.py
.\traffic\tests.py
- 개발 사항
버스 생성 관련 테스트를 위한 테스트 코드
- 정상 생성 테스트
- 출발지와 도착지가 같을 경우 테스트
- 출발시간이 도착시간보다 늦을 경우 테스트
- 출발시간이 현재시간보다 빠를 경우 테스트
- 도착시간이 현재시간보다 빠를 경우 테스트
- 출발시간이 현재시간과 같을 경우 테스트
- 도착시간이 현재시간과 같을 경우 테스트
정상 생성 테스트에 필요한 url, API, serializer 개발
- 테스트 명령어
python manage.py test traffic.tests.TestTrafficCase
> ✨ Feat: 버스 생성 기능

- account/models.py
- 수정 파일 .\account\models.py
- 수정 사항 슈퍼 유저 확인을 위한 has_module_perms, has_perm 함수 추가
> :sparkles: Feat: 사용자 모델 슈퍼유저 확인 메서드

- traffic/tests/test_bus.py
- traffic/tests/test_train.py
- traffic/views.py
- 수정 파일 
.\traffic\tests\test_bus.py
.\traffic\tests\test_train.py
- 수정 사항 
관리자와 일반 사용자 버스, 기차 생성 테스트 및 인증 설정
> :sparkles: Feat: 관리자, 일반 사용자 생성 테스트

- README.md
- 수정 파일 README.md
- 수정 사항 API 명세서 수정
> :memo: Doc: README.md API명세서 수정

- account/views.py
- pick/tests.py
- pick/views.py
- utils/permissions.py
- 개발 사항
- 본인이 찜한 숙소 목록 조회 기능 개발
- 테스트 사항
- 미로그인 상태에서 숙소 찜 리스트 조회 요청 테스트 - 로그인 상태에서 본인 숙소 찜 리스트 조회 요청 테스트
- 테스트 명령어
- `python manage.py test pick.tests.TestPick.test_pick_lodging_list`
> :sparkles: Feat: 숙소 찜 목록 API

- README.md
- pick/serializers.py
- pick/tests.py
- pick/urls.py
- pick/views.py
- 개발 사항
- 로그인한 사용자 대상 기차 찜 생성 기능 개발
- 로그인한 사용자 대상 본인의 기차 찜 목록 조회 기능 개발
- 로그인한 사용자 대상 본인이 등록한 기차 찜 삭제 기능 개발
- 로그인한 사용자 대상 기차 찜 생성 기능 개발
- 로그인한 사용자 대상 본인의 렌트카 찜 목록 조회 기능 개발
- 테스트 사항
- 미로그인 상태에서 기차 찜 생성 요청 테스트
- 로그인 상태에서 기차 찜 생성 요청 테스트
- 중복 생성 요청 테스트
- 미로그인 상태에서 기차 찜 리스트 조회 요청 테스트
- 로그인 상태에서 본인 기차 찜 리스트(찜 목록이 있는 경우) 조회 요청 테스트
- 로그인 상태에서 본인 기차 찜 리스트(찜 목록이 없는 경우) 조회 요청 테스트
- 미로그인 상태에서 기차 찜 삭제 요청 테스트
- 존재하지 않는 기차 찜 삭제 요청 테스트
- 다른 사용자의 기차 찜 삭제 요청 테스트
- 로그인 상태에서 본인 기차 찜 삭제 요청 테스트
- 미로그인 상태에서 기차 찜 생성 요청 테스트
- 로그인 상태에서 기차 찜 생성 요청 테스트
- 중복 생성 요청 테스트
- 미로그인 상태에서 렌트카 찜 리스트 조회 요청 테스트
- 로그인 상태에서 본인 렌트카 찜 리스트(찜 목록이 있는 경우) 조회 요청 테스트
- 로그인 상태에서 본인 렌트카 찜 리스트(찜 목록이 없는 경우) 조회 요청 테스트
- 테스트 명령어
- `python manage.py test pick.tests.TestPickTrain.test_pick_train_create`
- `python manage.py test …
> :sparkles: Feat: 기차 찜 생성, 목록, 삭제, 렌트카 찜 생성, 목록 API

- traffic/models.py
- traffic/tests/test_bus.py
- traffic/tests/test_rentalcar.py
- traffic/tests/test_train.py
- 수정 파일 .\traffic\tests\test_bus.py
.\traffic\tests\test_train.py
.\traffic\tests\test_rentalcar.py
> :bug: Fix: 버스, 기차, 렌트카 테스트 오류 수정

- reservation/tests.py
- reservation/views.py
- 개발 사항
- 로그인한 사용자 대상 본인의 숙소 예약 목록 조회 기능 개발
- 테스트 사항 
- 미로그인 상태에서 숙소 예약 리스트 조회 요청 테스트 
- 로그인 상태에서 숙소 예약이 있는 경우 리스트 조회 요청 테스트 
- 로그인 상태에서 숙소 예약이 없는 경우 리스트 조회 요청 테스트
- 테스트 명령어 
- `python manage.py test reservation.tests.TestReservationLodging.test_reservation_lodging_list`
> :sparkles: Feat: 숙소 예약 목록 API

- traffic/serializers.py
- traffic/tests/test_rentalcar.py
- traffic/urls.py
- traffic/views.py
- 개발 사항 
렌트카 리뷰 답글 API 및 개발
- 테스트 사항
- 렌트카 리뷰 댓글 생성 테스트(일반 사용자)
- 비정상 처리 테스트 - 렌트카 리뷰 댓글 내용이 없을 경우
- 비정상 처리 테스트 - 존재하지 않는 렌트카 리뷰에 댓글 생성 시도
- 렌트카 리뷰 댓글 생성 테스트(로그인을 하지 않은 사용자)
- 렌트카 리뷰 댓글 리스트 테스트
- 렌트카 리뷰 댓글 수정 테스트(일반 사용자)
- 비정상 처리 테스트 - 존재하지 않는 렌트카 리뷰 댓글 수정 시도
- 비정상 처리 테스트 - 렌트카 리뷰 댓글 내용이 없을 경우
- 렌트카 리뷰 댓글 수정 테스트(로그인을 하지 않은 사용자)
- 비정상 처리 테스트 - 로그인을 하지 않은 사용자가 렌트카 리뷰 댓글 수정 시도
- 렌트카 리뷰 댓글 삭제 테스트(일반 사용자)
- 비정상 처리 테스트 - 존재하지 않는 렌트카 리뷰 댓글 삭제 시도
- 렌트카 리뷰 댓글 삭제 테스트(로그인을 하지 않은 사용자)
> :sparkles: Feat: 렌트카 리뷰 답글 API 개발 및 테스트

- README.md
- reservation/serializers.py
- reservation/tests.py
- reservation/views.py
- 개발 사항
- 로그인한 사용자 대상 본인의 숙소 예약 수정 기능 개발
- 테스트 사항
- 미로그인 상태에서 숙소 예약 수정 요청 테스트
- 로그인 상태(권한 X)에서 숙소 예약 수정 요청 테스트
- 로그인 상태(권한 O)에서 숙소 예약 수정 요청 테스트
- 이전 예약 날짜와 같은 예약 날짜로 수정 요청 테스트
- 예약 시작일이 예약 종료일보다 늦은 경우 테스트
- 예약 시작일이 예약 종료일과 같은 경우 테스트
- 예약 시작일이 과거 날짜인 경우 테스트
- 존재하지 않는 숙소에 예약 수정 요청 테스트
- 예약된 날짜에 예약 수정 요청 테스트
- 테스트 명령어 - `python manage.py test reservation.tests.TestReservationLodging.test_reservation_lodging_patch`
> :sparkles: Feat: 숙소 예약 수정 API

- README.md
> :memo: Doc: README API 명세서 수정

- lodging/serializers.py
- lodging/tests/test_lodging.py
- lodging/tests/test_lodging_comment.py
- lodging/tests/test_lodging_image.py
- lodging/tests/test_lodging_review.py
- lodging/tests/test_lodging_roomtype.py
- lodging/urls.py
- lodging/views.py
- 개발 사항
- 숙소 리뷰 댓글 생성
- 숙소 리뷰 댓글 조회
- 숙소 리뷰 댓글 수정
- 숙소 리뷰 댓글 삭제
- 테스트 내용
- 숙소 리뷰 댓글 생성 테스트 - 인증X
- 숙소 리뷰 댓글 생성 테스트 - 인증O
- 숙소 리뷰 댓글 생성 테스트 - 숙소 리뷰 없음
- 숙소 리뷰 댓글 생성 테스트 - 유저 없음
- 숙소 리뷰 댓글 수정 테스트 - 인증O
- 숙소 리뷰 댓글 수정 테스트 - 숙소 리뷰 없음
- 숙소 리뷰 댓글 수정 테스트 - 유저 없음
- 숙소 리뷰 댓글 수정 테스트 - 댓글 없음
- 숙소 리뷰 댓글 조회 테스트 - 인증O
- 숙소 리뷰 댓글 삭제 테스트 - 인증O
> :sparkles: Feat: 숙소 리뷰 댓글 crud 개발

- lodging/serializers.py
- lodging/tests/test_lodging_image.py
- lodging/tests/test_lodging_roomtype.py
- lodging/urls.py
- lodging/views.py
- 개발 사항
- 객실 이미지 생성, 삭제, 조회, 수정
- 테스트 사항
- 객실 타입 이미지 생성 - 비로그인
- 객실 타입 이미지 생성 - 권한 없는 유저
- 객실 타입 이미지 생성 - 권한 있는 유저
- 객실 타입 이미지 생성 - 이미지 미입력
- 객실 타입 이미지 생성 - 메인 이미지 중복 등록
- 객실 타입 이미지 생성 - 등록되지 않은 객실 타입
- 객실 타입 이미지 수정 - 비로그인
- 객실 타입 이미지 수정 - 권한 없는 유저
- 객실 타입 이미지 수정 - 권한 있는 유저
- 객실 타입 이미지 삭제 - 비로그인
- 객실 타입 이미지 삭제 - 권한 없는 유저
- 객실 타입 이미지 삭제 - 권한 있는 유저
- 객실 타입 이미지 삭제 - 없는 이미지
- 객실 타입 이미지 리스트
> :sparkles: Feat: 객실 이미지 CRUD API 개발

- lodging/serializers.py
- lodging/tests/test_lodging.py
- lodging/tests/test_lodging_amenity.py
- lodging/tests/test_lodging_comment.py
- lodging/tests/test_lodging_image.py
- lodging/tests/test_lodging_review.py
- lodging/tests/test_lodging_roomtype.py
- lodging/tests/test_setup.py
- lodging/urls.py
- lodging/views.py
- 리팩토링 내용
- test_setup.py에 setUp 메소드 정리
>  ✨ Feat: 숙소 편의시설 API 개발,  :test_tube: Test: 테스트 코드 리팩토링

- README.md
- reservation/serializers.py
- reservation/tests.py
- reservation/urls.py
- reservation/views.py
- 개발 사항
- 로그인한 사용자 대상 버스 예약 기능 개발
- 로그인한 사용자 대상 버스 예약 목록 기능 개발
- 로그인한 사용자 대상 버스 예약 삭제 기능 개발
- 테스트 사항
- 미로그인 상태에서 버스 예약 생성 요청 테스트
- 로그인 상태에서 버스 예약 생성 요청 테스트
- 이미 만원인 버스 예약 생성 요청 테스트
- 과거 날짜에 버스 예약 생성 요청 테스트
- 존재하지 않는 버스에 버스 예약 생성 요청 테스트
- 여러 좌석을 예약했을 때 예약 가능한 경우 테스트
- 여러 좌석을 예약했을 때 좌석이 부족한 경우 테스트
- 미로그인 상태에서 버스 예약 리스트 조회 요청 테스트
- 로그인 상태에서 버스 예약이 있는 경우 리스트 조회 요청 테스트
- 로그인 상태에서 버스 예약이 없는 경우 리스트 조회 요청 테스트
- 미로그인 상태에서 버스 예약 삭제 요청 테스트
- 로그인 상태(권한 X)에서 버스 예약 삭제 요청 테스트
- 로그인 상태(권한 O)에서 버스 예약 삭제 요청 테스트
- 존재하지 않는 버스 예약 삭제 요청 테스트
- 테스트 명령어
- `python manage.py test reservation.tests.TestReservationBus.test_reservation_bus_create`
- `python manage.py test reservation.tests.TestReservationBus.test_reservation_bus_list`
- `python manage.py test …
> :sparkles: Feat: 버스 예약 생성, 목록, 삭제 API & 📝 Doc: README 수정

- lodging/models.py
- lodging/serializers.py
- lodging/tests/test_lodging_location.py
- lodging/tests/test_setup.py
- lodging/urls.py
- lodging/views.py
- 개발 사항
- 숙소 메인 주소 CRUD
- 숙소 서브 주소 CRUD
- 테스트 내용
- 메인 지역 생성 테스트
- 메인 지역 조회 테스트
- 메인 지역 수정 테스트
- 메인 지역 삭제 테스트
- 서브 지역 생성 테스트
- 서브 지역 조회 테스트
- 서브 지역 수정 테스트
- 서브 지역 삭제 테스트
> :sparkles: Feat: 숙소 메인, 서브 주소 API 개발

- reservation/serializers.py
- reservation/tests.py
- reservation/urls.py
- reservation/views.py
- 개발 사항
- 로그인한 사용자 대상 기차 예약 생성 기능 개발
- 로그인한 사용자 대상 기차 예약 목록 기능 개발
- 로그인한 사용자 대상 기차 예약 삭제 기능 개발
- 테스트 사항
- 미로그인 상태에서 기차 예약 생성 요청 테스트
- 로그인 상태에서 기차 예약 생성 요청 테스트
- 이미 만원인 버스 기차 생성 요청 테스트
- 과거 날짜에 버스 기차 생성 요청 테스트
- 존재하지 않는 기차에 버스 예약 생성 요청 테스트
- 여러 좌석을 예약했을 때 예약 가능한 경우 테스트
- 여러 좌석을 예약했을 때 좌석이 부족한 경우 테스트
- 미로그인 상태에서 기차 예약 리스트 조회 요청 테스트
- 로그인 상태에서 기차 예약이 있는 경우 리스트 조회 요청 테스트
- 로그인 상태에서 기차 예약이 없는 경우 리스트 조회 요청 테스트
- 미로그인 상태에서 기차 예약 삭제 요청 테스트
- 로그인 상태(권한 X)에서 기차 예약 삭제 요청 테스트
- 로그인 상태(권한 O)에서 기차 예약 삭제 요청 테스트
- 존재하지 않는 기차 예약 삭제 요청 테스트
- 테스트 명령어
- `python manage.py test reservation.tests.TestReservationTrain.test_reservation_train_create`
- `python manage.py test reservation.tests.TestReservationTrain.test_reservation_train_list`
- `python manage.py test …
> :sparkles: Feat: 기차 예약 생성, 목록, 삭제 API

- reservation/serializers.py
- reservation/tests.py
- reservation/urls.py
- reservation/views.py
- 개발 사항
- 로그인한 사용자 대상 렌트카 예약 생성 기능 개발
- 로그인한 사용자 대상 렌트카 예약 목록 기능 개발
- 로그인한 사용자 대상 렌트카 예약 수정 기능 개발
- 로그인한 사용자 대상 렌트카 예약 삭제 기능 개발
- 테스트 사항
- 미로그인 상태에서 렌트카 예약 생성 요청 테스트
- 로그인 상태에서 렌트카 예약 생성 요청(1박 2일) 테스트
- 로그인 상태에서 렌트카 예약 생성 요청(2박 3일) 테스트
- 이미 예약된 날짜에 렌트카 예약 생성 요청 테스트
- 과거 날짜에 렌트카 예약 생성 요청 테스트
- 존재하지 않는 렌트카에 렌트카 예약 생성 요청 테스트
- 예약 시작일이 예약 종료일보다 늦은 경우 테스트
- 렌트카 예약 시간이 09:00 ~ 18:00이 아닌 경우 테스트
- 미로그인 상태에서 렌트카 예약 리스트 조회 요청 테스트
- 로그인 상태에서 렌트카 예약이 있는 경우 리스트 조회 요청 테스트
- 로그인 상태에서 렌트카 예약이 없는 경우 리스트 조회 요청 테스트
- 미로그인 상태에서 렌트카 예약 수정 요청 테스트
- 로그인 상태(권한 X)에서 렌트카 예약 수정 요청 테스트
- 로그인 상태(권한 O)에서 렌트카 예약 수정 요청 테스트
- 이전 예약 날짜와 같은 예약 날짜로 수정 요청 테스트
- 예약 시작일이 예약 종료일보다 늦은 경우 테스트
- 예약 시작일이 예약 종료일과 같은 경우 테스트
- 예약 시작일이 과거 날짜인 경우 테스트
- 존재하지 않는 렌트카에 예약 수정 요청 테스트
- 예약된 날짜에 예약 수정 요청 테스트
- 미로그인 상태에서 렌트카 예약 삭제 요청 테스트
- 로그인 …
> :sparkles: Feat: 렌트카 예약 생성, 목록, 수정, 삭제 API

- traffic/serializers.py
- traffic/tests/test_rentalcar.py
- traffic/urls.py
- traffic/views.py
- 개발 사항
렌트카 리뷰 이미지 생성 및 삭제 API
- 테스트 사항
렌트카 리뷰 이미지 생성 테스트(일반 사용자)
렌트카 리뷰 이미지 생성 테스트(로그인을 하지 않은 사용자)
렌트카 리뷰 이미지 삭제 테스트(일반 사용자)
렌트카 리뷰 이미지 삭제 테스트(로그인을 하지 않은 사용자)
> ✨ Feat: 렌트카 리뷰 이미지 생성, 삭제 API 개발 및 테스트

- lodging/models.py
- lodging/serializers.py
- nolreo_wassup/settings.py
- 수정 사항
LodgingSerializer amenities필드 수정
settings.py ALLOWED_HOSTS '127.0.0.1' 추가
> :bug: Fix: serializers.py 수정

- account/serializers.py
- account/views.py
- lodging/serializers.py
- 수정 사항
account views.py, serializers.py nickname 수정
lodging serializers.py 리뷰id 수정
> :bug: Fix: account, lodging 수정
